name: feewu
description: 物有所值

publish_to: none

version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
